export const CHECKLOGIN = 'CHECKLOGIN';
export const CHECKLOGINSUCCESS = 'CHECKLOGINSUCCESS';

export const LOGIN = 'LOGIN';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAIL = 'LOGINFAIL';

export const CREATEACCOUNT = 'CREATEACCOUNT';
export const CREATEACCOUNTSUCCESS = 'CREATEACCOUNTSUCCESS';
export const CREATEACCOUNTFAIL = 'CREATEACCOUNTFAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUTSUCCESS = 'LOGOUTSUCCESS';
export const LOGOUTFAIL = 'LOGOUTFAIL';

export const HANDLEINPUTCHANGE = 'HANDLEINPUTCHANGE';
